name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "🧰 Maintenance"
    label:
      - "chore"
      - "refactor"
      - "test"
      - "environment"
  - title: "✨ Styles"
    labels:
      - "design"
  - title: "🛠️ Build"
    labels:
      - "build"
      - "ci"
autolabeler:
  - label: "feature"
    branch:
      - '/feat\/.+/'
    title:
      - "/feat:/i"
  - label:
      - "fix"
      - "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix:/i"
  - label: "design"
    branch:
      - '/design\/.+/'
    title:
      - "/design:/i"
  - label: "refactor"
    branch:
      - '/refactor\/.+/'
    title:
      - "/refactor:/i"
  - label: "chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore:/i"
  - label: "docs"
    branch:
      - '/docs\/.+/'
    title:
      - "/docs:/i"
  - label: "build"
    branch:
      - '/build\/.+/'
    title:
      - "/build:/i"
  - label: "ci"
    branch:
      - '/ci\/.+/'
    title:
      - "/ci:/i"
  - label: "perf"
    branch:
      - '/perf\/.+/'
    title:
      - "/perf:/i"
  - label: "test"
    branch:
      - '/test\/.+/'
    title:
      - "/test:/i"
  - label: "style"
    branch:
      - '/style\/.+/'
    title:
      - "/style:/i"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
