import type { Metadata } from "next"
import { inter } from "@ui/fonts"
import "@ui/globals.css"
import AuthContext from "@context/AuthContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  )
}
