import type { Metadata } from "next"
import { Experimental_CssVarsProvider as CssVarsProvider } from "@mui/material/styles"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import { CssBaseline } from "@mui/material"
import AuthContext from "@context/AuthContext"
import { pretend } from "@ui/fonts"
import theme from "@ui/theme"
import "@ui/globals.css"

export const metadata: Metadata = {
  title: "Hello Charlie!",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={pretend.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <CssVarsProvider theme={theme}>
            <CssBaseline />
            <AuthContext>{children}</AuthContext>
          </CssVarsProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
