import type { Metadata } from "next"
import { CssBaseline } from "@mui/material"
import { Experimental_CssVarsProvider as ThemeProvider } from "@mui/material/styles"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import { inter } from "@ui/fonts"
import AuthContext from "@context/AuthContext"
import theme from "@ui/theme"
import "@ui/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <AuthContext>{children}</AuthContext>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
